### ISSUE TITLE
画面構造を作成する。

### ISSUE THREAD

**Issue by Mori-Atsushi** [Mori-Atsushi/SyncPod-iOS#6]
以下の空画面を作成する
* main画面（初期起動画面、トップ画面への遷移を分ける）
* 初回起動画面
* ログイン画面
* 新規登録画面
* トップ画面
* ルーム画面
* 動画検索画面

**Comment by chigichan24** [comment]
取り敢えずボタンをおいて遷移も実装しますか？

**Comment by Mori-Atsushi** [comment]
うーん、なくてもいいと思ってたけど。
どうせこれ作ってから、初回起動画面、ログイン画面…って画面遷移の順番に実装していくし

**Comment by chigichan24** [comment]
じゃあ雑にscene作るだけ作るのでいいか
